replicaCount: 1

image:
  repository: exchange-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8085

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: exchange.myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  database_url: "jdbc:postgresql://{{ .Release.Name }}-common-db:5432/commondb"
  database_username: "common_user"
  spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"

secret:
  enabled: true
  name: exchange-secret
  data:
    SPRING_DATASOURCE_PASSWORD: postgres