server:
  port: 8085

spring:
  application:
    name: exchange-service
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "consul:"

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.consul: DEBUG
