server:
  port: 8085

spring:
  application:
    name: exchange-service
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "optional:consul:"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-app

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: exchange_schema
    show-sql: true
  flyway:
    enabled: true
    schemas: exchange_schema
    locations: classpath:/db/migration

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.springframework.security: DEBUG
