server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "consul:"
    gateway:
      mvc:
        routes:
          - id: accounts-service
            uri: lb://accounts-service
            predicates:
              - Path=/accounts/**

          - id: blocker-service
            uri: lb://blocker-service
            predicates:
              - Path=/blocker/**
            filters:
              - RewritePath=/blocker/?(?<segment>.*), /$\{segment}

          - id: cash-service
            uri: lb://cash-service
            predicates:
              - Path=/cash/**
            filters:
              - RewritePath=/cash/?(?<segment>.*), /$\{segment}

          - id: exchange-generator-service
            uri: lb://exchange-generator-service
            predicates:
              - Path=/exchange-generator/**
            filters:
              - RewritePath=/exchange-generator/?(?<segment>.*), /$\{segment}

          - id: exchange-service
            uri: lb://exchange-service
            predicates:
              - Path=/exchange/**
            filters:
              - RewritePath=/exchange/?(?<segment>.*), /$\{segment}

          - id: front-ui
            uri: lb://front-ui
            predicates:
              - Path=/front-ui/**
            filters:
              - RewritePath=/front-ui/?(?<segment>.*), /$\{segment}

          - id: notification-service
            uri: lb://notification-service
            predicates:
              - Path=/notification/**
            filters:
              - RewritePath=/notification/?(?<segment>.*), /$\{segment}

          - id: transfer-service
            uri: lb://transfer-service
            predicates:
              - Path=/transfer/**
            filters:
              - RewritePath=/transfer/?(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.consul: DEBUG
