version: '3.8'

# this docker-compose is used for local development

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-server-improvements
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  consul:
    image: hashicorp/consul:1.20
    container_name: consul-for-local
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    volumes:
      - ./init-consul.sh:/init-consul.sh
      - ./data:/data
    # chmod +x init-consul.sh
    entrypoint: /init-consul.sh

  db:
    image: postgres:15
    container_name: postgres-for-local
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: