server:
  port: 8083

spring:
  application:
    name: cash-service
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "consul:"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-app

      client:
        registration:
          cash-service:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: cash-service_m2m
            client-secret: ZkXS0uBiuTdDkUl0iONVxlWZkLN2E3oR
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank-app/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.springframework.security: DEBUG
    io.github.resilience4j.retry: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      accountCircuitBreaker, updateCircuitBreaker, checkBlockCircuitBreaker, notifyCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

  retry:
    instances:
      accountRetry, updateRetry, checkBlockRetry, notifyRetry:
        max-attempts: 3
        wait-duration: 1s

# todo: put property into consul
blocker-service:
  url: http://api-gateway/blocker/check
notification-service:
  url: http://api-gateway/notification/notify
account-service:
  url: http://api-gateway/accounts/accounts