server:
  port: 8084

spring:
  application:
    name: exchange-generator-service
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "consul:"

  security:
    oauth2:
      client:
        registration:
          exchange-generator-service:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: exchange-generator-service_m2m
            client-secret: juV1s9b0KlrXQfs5QoQAjhsTnItkToxw
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank-app/protocol/openid-connect/token

resilience4j:
  circuitbreaker:
    instances:
      sendRateToExchangeServiceBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

  retry:
    instances:
      sendRateToExchangeServiceRetry:
        max-attempts: 3
        wait-duration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.consul: DEBUG

# todo: put property into consul
exchange-service:
  url: http://api-gateway/exchange/rates

currency:
  pairs:
    [USD, EUR, CNY]
  range:
    USD: {min: 80, max: 90}
    EUR: {min: 85, max: 100}
    CNY: {min: 11, max: 11.5}