replicaCount: 1

image:
  repository: front-ui
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8086

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: front-ui.myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
  account_service_profile_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/profiles"
  account_service_account_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/accounts"
  account_service_general_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081"
  cash_service_url: "http://bank-app-cash-service.{{ .Release.Namespace }}.svc.cluster.local:8083"
  transfer_service_url: "http://bank-app-transfer-service.{{ .Release.Namespace }}.svc.cluster.local:8088"
  exchange_service_url: "http://bank-app-exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8085"

secret:
  enabled: true
  name: front-ui-secret
  data:
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FRONT_UI_CLIENT_ID: front-ui_m2m
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FRONT_UI_CLIENT_SECRET: sP4ME81qdYK23nMz4CV7AxT52KUeqBJj
    SECURITY_JWT_SECRET: wj38dKSk4Xpe49TrsTcv82yNvmz1qKwLZnUp1fZ5U7A=