
replicaCount: 1

image:
  repository: exchange-generator-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: exchange-generator.myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
  exchange_service_url: "http://bank-app-exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8085/rates"

secret:
  enabled: true
  name: exchange-generator-secret
  data:
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_SERVICE_CLIENT_ID: exchange-generator-service_m2m
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: juV1s9b0KlrXQfs5QoQAjhsTnItkToxw

