server:
  port: 8086

spring:
  application:
    name: front-ui
  cloud:
    consul:
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: yaml
  config:
    import: "consul:"

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

security:
  jwt:
    secret: wj38dKSk4Xpe49TrsTcv82yNvmz1qKwLZnUp1fZ5U7A=

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.consul: DEBUG
