replicaCount: 1

image:
  repository: cash-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: cash.myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    blocker_service_url: "http://bank-app-blocker-service.{{ .Release.Namespace }}.svc.cluster.local:8082/check"
    notification_service_url: "http://bank-app-notification-service.{{ .Release.Namespace }}.svc.cluster.local:8087/notify"
    account_service_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/accounts"

secret:
  enabled: true
  name: cash-secret
  data:
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_ID: cash-service_m2m
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: ZkXS0uBiuTdDkUl0iONVxlWZkLN2E3oR