server:
  port: 8088

spring:
  application:
    name: transfer-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-app

      client:
        registration:
          transfer-service:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: transfer-service_m2m
            client-secret: WT1ALa0PSEiUhNGwbZsCtvYGXasTGCJz
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank-app/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health ,  refresh
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG
    io.github.resilience4j.retry: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      accountCircuitBreaker, updateCircuitBreaker, checkBlockCircuitBreaker, exchangeCircuitBreaker, notifyCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

  retry:
    instances:
      accountRetry, updateRetry, checkBlockRetry, exchangeRetry, notifyRetry:
        max-attempts: 3
        wait-duration: 1s

# properties previously residing in consul:
blocker-service:
  url: http://localhost:8082/check
notification-service:
  url: http://localhost:8087/notify
account-service:
  url: http://localhost:8081/accounts
exchange-service:
  url: http://localhost:8085