apiVersion: v2
name: bank-app-helm-chart
description: A Helm chart for Kubernetes (umbrella-structured)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  # Subchart for Notification Service
  - name: notification-service
    version: "0.1.0"
    repository: "file://./charts/notification-service" # Local path reference

  # Dependency for Notification DB (e.g., PostgreSQL)
  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: notification-db # Alias to distinguish this instance
    condition: notification-db.enabled # Allow disabling if needed

  # Dependency for security service (Keycloak)
  - name: keycloak
    version: "24.8.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: keycloak
    condition: keycloak.enabled