# Default values for bank-app-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values (if any)
global:
  domain: myapp.local # Example domain for ingress

# Configuration for the common-db (PostgreSQL dependency)
# Values here are prefixed according to the Bitnami PostgreSQL chart's structure
# Check the Bitnami chart's values.yaml for all available options
common-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: commondb
    username: common_user
    # Use existingSecret or provide password (less secure for production)
    existingSecret: "{{ .Release.Name }}-common-db-postgresql" # Name of the secret to use/create
  #    password: "changeM3Notification!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: admin
#    existingSecret: ""
    createAdminUser: true
  postgresql:
    auth:
      username: bn_keycloak
      password: "mySuperSecretPass"
  service:
    type: ClusterIP
    ports:
      http: 8080
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: keycloak.myapp.local
    path: /
    pathType: ImplementationSpecific
  keycloakConfigCli:
    enabled: true
    existingConfigmap: bank-app-keycloak-realm
  realmConfig:
    enabled: true
    realmFile: files/realm-export.json
  extraEnvVars:
    - name: KC_HOSTNAME
      value: bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local
    - name: KC_HOSTNAME_STRICT
      value: "true"

# Configuration for the notification-service subchart
# NOTE: For local development (Minikube/Kind/Docker Desktop), build the image locally
# (e.g., `docker build -t notification-service:0.0.1-SNAPSHOT .` in notification-service dir)
# and ensure your K8s cluster can access local images (e.g., `minikube docker-env` or `kind load docker-image ...`).
notification-service:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: notification-service # Removed registry prefix
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.1-SNAPSHOT"
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8087
  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    enabled: true
    className: "nginx" # Specify your ingress controller class
    hosts:
      - host: notification.myapp.local # Use global domain or specific
        paths:
          - path: /
            pathType: ImplementationSpecific
  # Database connection details and other envs passed to notification-service configmap
  config:
    # --- CORRECTED DB URL --- Using '<ReleaseName>-<Alias>' service name convention
    database_url: "jdbc:postgresql://{{ .Release.Name }}-common-db:5432/commondb"
    # Secret reference for password is more secure
    database_username: "common_user"
    # database_password_secret: "{{ .Release.Name }}-common-db-postgresql" # Reference to secret created by DB chart
    # database_password_secret_key: "postgresql-password" # Key within the secret
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"
  #    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.bank-app-develop.svc.cluster.local:8080/realms/bank-app"
  # Database connection details passed to notification-secret secret
  secret:
    enabled: true
    name: notification-secret
    data:
      SPRING_DATASOURCE_PASSWORD: postgres

exchange-service:
  replicaCount: 1
  image:
    repository: exchange-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8085
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: exchange.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-common-db:5432/commondb"
    database_username: "common_user"
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"

  secret:
    enabled: true
    name: exchange-secret
    data:
      SPRING_DATASOURCE_PASSWORD: postgres

exchange-generator-service:
  replicaCount: 1
  image:
    repository: exchange-generator-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8084
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: exchange-generator.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    exchange_service_url: "http://bank-app-exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8085/rates"

  secret:
    enabled: true
    name: exchange-generator-secret
    data:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_SERVICE_CLIENT_ID: exchange-generator-service_m2m
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: juV1s9b0KlrXQfs5QoQAjhsTnItkToxw

blocker-service:
  replicaCount: 1
  image:
    repository: blocker-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: blocker.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"

transfer-service:
  replicaCount: 1
  image:
    repository: transfer-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8088
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: transfer.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    blocker_service_url: "http://bank-app-blocker-service.{{ .Release.Namespace }}.svc.cluster.local:8082/check"
    notification_service_url: "http://bank-app-notification-service.{{ .Release.Namespace }}.svc.cluster.local:8087/notify"
    account_service_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/accounts"
    exchange_service_url: "http://bank-app-exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8085"

  secret:
    enabled: true
    name: transfer-secret
    data:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_ID: transfer-service_m2m
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_SECRET: WT1ALa0PSEiUhNGwbZsCtvYGXasTGCJz

cash-service:
  replicaCount: 1
  image:
    repository: cash-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: cash.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    blocker_service_url: "http://bank-app-blocker-service.{{ .Release.Namespace }}.svc.cluster.local:8082/check"
    notification_service_url: "http://bank-app-notification-service.{{ .Release.Namespace }}.svc.cluster.local:8087/notify"
    account_service_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/accounts"

  secret:
    enabled: true
    name: cash-secret
    data:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_ID: cash-service_m2m
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: ZkXS0uBiuTdDkUl0iONVxlWZkLN2E3oR

accounts-service:
  replicaCount: 1
  image:
    repository: accounts-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: accounts.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-common-db:5432/commondb"
    database_username: "common_user"
    spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app"
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    notification_service_url: "http://bank-app-notification-service.{{ .Release.Namespace }}.svc.cluster.local:8087/notify"

  secret:
    enabled: true
    name: accounts-secret
    data:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_CLIENT_ID: accounts-service_m2m
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_CLIENT_SECRET: vVwOHF8UY8Oah9a3aZGSt0GgyK1BflDI
      SPRING_DATASOURCE_PASSWORD: postgres
      SECURITY_JWT_SECRET: wj38dKSk4Xpe49TrsTcv82yNvmz1qKwLZnUp1fZ5U7A=

front-ui-service:
  replicaCount: 1
  image:
    repository: front-ui
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8086
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: front-ui.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    spring_security_oauth2_client_provider_keycloak_token_uri: "http://bank-app-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank-app/protocol/openid-connect/token"
    account_service_profile_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/profiles"
    account_service_account_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081/accounts"
    account_service_general_url: "http://bank-app-accounts-service.{{ .Release.Namespace }}.svc.cluster.local:8081"
    cash_service_url: "http://bank-app-cash-service.{{ .Release.Namespace }}.svc.cluster.local:8083"
    transfer_service_url: "http://bank-app-transfer-service.{{ .Release.Namespace }}.svc.cluster.local:8088"
    exchange_service_url: "http://bank-app-exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8085"

  secret:
    enabled: true
    name: front-ui-secret
    data:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FRONT_UI_CLIENT_ID: front-ui_m2m
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FRONT_UI_CLIENT_SECRET: sP4ME81qdYK23nMz4CV7AxT52KUeqBJj
      SECURITY_JWT_SECRET: wj38dKSk4Xpe49TrsTcv82yNvmz1qKwLZnUp1fZ5U7A=